- hosts: workstation
  gather_facts: false
  tasks:
  #Obtain information of frontend server
  - name: OpenStack servers
    os_server_info:
     cloud: ospcloud
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke
  
  #open the URL to open index.html and test the service http
  - name: URL website
    uri:
     url: "http://{{ openstack_info.openstack_servers[0].accessIPv4 }}"
     return_content: yes
     status_code: 200
    register: webpage
    tags:
      - osp.smoke
  
  #Print in log the content of index.html
  - debug: var=webpage.content
  
  #Check if text 'Ansible has ....' is present in index.html
  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.content"
    tags:
      - osp.smoke
