---
# tasks file for db-tier
- name: install postgres
  yum:
    name: postgresql-server
    state: latest

- name: enable postgres at boot
  service:
    name: postgresql
    enabled: yes

- name: tell user to finish setting up postgres
  debug:
   msg: "Either uncomment the postgres setup or manually login and initial"

# only run the next 2 tasks once!

- name: Clean data directory postgres. 
  file:
   path: /var/lib/pgsql/data/
   state: absent

- name: Create data directory postgres.
  file:
   path:  /var/lib/pgsql/data/
   owner: postgres
   group: postgres
   mode:  0700
   state: directory

- name: initilize postgres
  command: postgresql-setup initdb
 

- name: initilize postgres some more
  command: chkconfig postgresql on

- name: start postgres
  service:
    name: postgresql.service
    state: started


