---
# tasks file for db-tier
- name: Install postgres
  yum:
    name: postgresql-server
    state: latest

- name: Enable postgres at boot
  service:
    name: postgresql
    enabled: yes

- name: Initilize postgres
  command: postgresql-setup initdb
 

- name: Initilize postgres some more
  command: chkconfig postgresql on

- name: Start postgres
  service:
    name: postgresql.service
    state: started


